# Set base URL for site - should end with a trailing slash
baseUrl = "https://example.org/"

# theme = "slick"
theme = "PaperMod"

# Site title (not shown if commented out or set to false)
# (If you disable this, add some link on the index page inside menu.main,
#  otherwise your visitors will get confused and lost...)
title = "RainFD's Blog"

languageCode = "en"
defaultContentLanguage = "en"

# Will appear below the footer links with a © sign and the current year
copyright = "RainFD.com | Powered by Hugo | Based on Theme: Slick"

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true               # Allow html (needed for some shortcodes)
    [markup.highlight]
        codeFences = true               # Enable highlighting inside codefences
        guessSyntax = true              # Highlight code without language tag
        noClasses = false               # Use the theme's style sheet

canonifyURLs = true

# Configure pagination
paginate = 10
paginatePath = "page"

[params]
    # 备案号
    icp = "粤ICP备2022020499号"

    # Site subtitle (not shown if commented out or set to false)
    subtitle = ""

    # Site description
	description = "RainFD的个人博客."

    # Favicon file (relative to baseURL - place in assets folder)
    favicon = "favicon.png"
    # Deprecated feature - this is just here to check the deprecation notice!
    css = "custom.css"

    # Define formatting of dates
    # (optional, falls back to RFC822 format if not set)
    # For reference to date and time formatting, see:
    # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
    # Make sure to set showMetaDates to true to see any dates
    # dateFmt = "Mon, 02 Jan 2006"
    dateFmt = "2006 01/02"

    # Customize the text of the 404 page here
    # errorPageText = "There's nothing to see here, please move along!"
    errorPageText = "Nothing"

    # Define ordering by parameter - anything from the frontmatter is possible
    # Popular options would be "date" (default), "weight", "title", "publishdate"
    orderPageParam = "date"
    # Reverse the ordering from above
    orderPageReverse = true

    # Header with title/subtitle can be disabled here.
    # (If you disable this, add some link on the index page inside menu.main,
    #  otherwise your visitors will get confused and lost...)
    showNavHeader = true

    # If false the RSS link in footer is not shown
    showRssLink = true

    # Decide if only summaries are shown on the main page or the full content
    showFullContent = false

    # If false no pagination is shown when there is nothing to paginate
    showEmptyPagination = true

    # If false the title, dates and taxonomy are not shown on single view
    showMeta = true

    # If false the dates for the posts are not shown
    showMetaDates = true

    # If false the taxonomy links for the posts are not shown
    showMetaLinks = true

    # Uses Hugo internal templates if set
    opengraph = false
    schema = false
    twitter_cards = false


# Define all supported taxonomies (add series to the default)
[taxonomies]
    tags = "tags"
    categories = "categories"
    series = "series"


[author]
    name = "Some Author"
    email = "mail@example.org"


[services.rss]
    # limit the length of the rss feed (default: unlimited)
    limit = 0

# slick theme menu
[menu]

    # Configure main menu entries (header)
    # Currently set to list all taxonomies and posts
    [[menu.main]]
        identifier = "post"
        name = "Posts"
        title = "All posts"
        pageref = "/posts"
        weight = 1

    [[menu.main]]
        identifier = "categories"
        name = "Categories"
        title = "All categories"
        pageref = "/categories"
        weight = 2

    [[menu.main]]
        identifier = "tags"
        name = "Tags"
        title = "All tags"
        pageref = "/tags"
        weight = 2

    [[menu.main]]
        identifier = "series"
        name = "Series"
        title = "All series"
        pageref = "/series"
        weight = 2


    # Define the entries for post metadata
    # Identifiers should match with the taxonomy entries
    [[menu.meta]]
        identifier = "categories"
        name = "Categories"
        weight = 1
    [[menu.meta]]
        identifier = "series"
        name = "Series"
        weight = 2
    [[menu.meta]]
        identifier = "tags"
        name = "Tags"
        weight = 3


    # Add some footer links to your likings
    [[menu.footer]]
        name = "GitHub"
        title = "RainFD repository"
        url = "https://github.com/rainfd"
        weight = 1

    [[menu.footer]]
        name = "Slick"
        title = "Theme page on gohugo.io"
        url = "https://themes.gohugo.io/slick"
        weight = 2


# Enable generation of robots.txt
enableRobotsTXT = true

# Configure sitemap
[sitemap]
  # Values are 'always', 'hourly', 'daily',' weekly', 'monthly', 'yearly',
  # and 'never'. Set to empty string to omit inclusion
  changefreq = "monthly"
  # Adjust filename of sitemap. (default: sitemap.xml)
  filename = "sitemap.xml"
  # Values range from 0.0 to 1.0. Set to -1 to omit inclusion
  priority =  -1


[module]
  [[module.imports]]
    path = 'github.com/adityatelange/hugo-PaperMod'